import Chair from '../assets/images/chair.png'
import Sofa from '../assets/images/sofa.png'
import SofaAll from '../assets/images/sofa-all.png'
import Vase from '../assets/images/vase.png'
import Poter from './images/poter.png'
import Poter1 from './images/poter-one.png'
import Lamp from './images/lamp.png'
import Table from './images/table.png'
import Flower from './images/flower.png'
import SofaWall from './images/sofa-wall.png'
export { Chair, Sofa, SofaAll, Vase, Poter, SofaWall, Flower, Poter1, Lamp, Table }